import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Header } from './components/Header'
import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';


const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}

{
  /* <div className="flex flex-col min-h-screen">
<Header />
<main className="flex flex-col flex-1 bg-muted/50" style={{ backgroundColor:'#f6f9fd' }} 
>{children}
<SpeedInsights />
</main>
</div> */
}

// return (
//   <html lang="en">
//     <body
//       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//     >
//       <div className="flex flex-col min-h-screen">
//         <Header />
//         <main
//           className="flex flex-col flex-1 bg-muted/50"
//           style={{ backgroundColor: '#f6f9fd' }}
//         >
//           {children}
//         </main>
//       </div>
//     </body>
//   </html>
// );
